[package]
name = "perorustbot"
version = "0.1.2"
license = "MIT"
description = "My personal telegram bot in rust"
homepage = "https://github.com/PeroSar/perorustbot"
authors = ["PeroSar <perosar1111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.4.0", features = ["auto-send", "macros"] }
log = "0.4.8"
pretty_env_logger = "0.4.0"
tokio = { version =  "1.3", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.3", features = ["json"] }
serde_json = "1.0.50"
